# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a8e28a92db35882cb483b9b29a15fe8b78b3f4fe770c7c255ec0772b0ff82198f34b062e78b37546ae6e7153bff23bf2b874533189f9e61ccc358a48bebabe8

test:
  secret_key_base: 37c7300ea2d924474847936ab2680612c5e60d5d6d95b1cbc81c8d9f6efa522f5682d8085e7dbc8a51018a22b5cd1506ddc87beba280dffe48782796b3713a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
